config/routes.rb
Rails.application.routes.draw do
  resources :ingredients
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  attr_accessor :image_cache
  has_one_attached :image
  validates :name, presence: true, uniqueness: true, length: { maximum:160}
  validates :expiry, presence: true
  validate :number_or_amount
  # mount_uploader :image, ImageUploader
  validates :image,   content_type: { in: %w[image/jpeg image/gif image/png],
                                      message: "must be a valid image format" },
                      size:         { less_than: 5.megabytes,
                                      message: "should be less than 5MB" }

  # 表示用のリサイズ済み画像を返す
  def display_image
    image.variant(resize_to_fill: [200, 100])
  end


  private 

  def number_or_amount
    return if amount.present? ^ number.present?

    errors.add(:number, 'か重量どちらかを入力してください')
    errors.add(:amount, 'か個数どちらかを入力してください')
  end  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
  def index
    @ingredients_pagination = Ingredient.paginate(page: params[:page], per_page: 12)
    @q = @ingredients_pagination.ransack(params[:q])
    @ingredients = @q.result.page(params[:page]).order("created_at desc")
  end

  def show
    @ingredient = Ingredient.find(params[:id])

    respond_to do |format|
      format.html
      format.js
    end
  end

  def new
    @ingredient = Ingredient.new
  end

  def create
    @ingredient = Ingredient.new(ingredient_params)
    @ingredient.image.attach(params[:ingredient][:image])
    if @ingredient.save
      redirect_to ingredients_path, notice: 'Success'
    else
      flash.now[:alert] = "Error"
      render :new
    end
  end

  def edit
    @ingredient = Ingredient.find(params[:id])
  end

  def update
    @ingredient = Ingredient.find(params[:id])
    @ingredient.image.attach(params[:ingredient][:image])
    if @ingredient.update(ingredient_params)
      redirect_to ingredients_path
    else
      flash.now[:alert] = "Error"
      render 'edit'
    end
  end

  def destroy
    Ingredient.find(params[:id]).destroy
    flash.now[:success] = "Movie deleted"
    redirect_to ingredients_path
  end

  private

  def ingredient_params
    params.require(:ingredient).permit(:name, :expiry, :number, :amount, :image)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/helpers/with_error_form_builder.rb
class WithErrorFormBuilder < ActionView::Helpers::FormBuilder
  def pick_errors(attribute)
    return nil if @object.nil? || (messages = @object.errors.messages[attribute]).nil?

    lis = messages.collect do |message|
      %{#{@object.errors.full_message(attribute, message)}}
    end.join

    %{<div class="errors_parent"><ul class="errors">#{lis}</ul></div>}.html_safe
  end

  def text_field(attribute, options={})
    return super if options[:no_errors]
    super + pick_errors(attribute)
  end

  def email_field(attribute, options={})
    return super if options[:no_errors]
    super + pick_errors(attribute)
  end

  def password_field(attribute, options={})
    return super if options[:no_errors]
    super + pick_errors(attribute)
  end

  def date_field(attribute, options={})
    return super if options[:no_errors]
    super + pick_errors(attribute)
  end

  def number_field(attribute, options={})
    return super if options[:no_errors]
    super + pick_errors(attribute)
  end

  def amount_field(attribute, options={})
    return super if options[:no_errors]
    super + pick_errors(attribute)
  end    

end

app/views/ingredients/edit.html.erb
<h1>Ingredient Change</h1>

<div>
  <div class="container">
    <div class="row justify-content-md-center">
        <%= form_with(model: @ingredient, builder: WithErrorFormBuilder, url: ingredient_path(@ingredient), class: "col-md-auto", local: true) do |f| %>
          <%# <%= render 'shared/error_messages', model: f.object %>
          <%= f.label :name, '食材' %> <%= f.text_field :name, class: 'form-control' %></br>
          <%= f.label :expiry, '賞味期限' %> <%= f.date_field :expiry, class: 'form-control'%></br>
          <%= f.label :number, '個数' %> <%= f.number_field :number, class: 'form-control'%></br>
          <%= f.label :amount, '重量(g)' %> <%= f.number_field :amount, class: 'form-control'%></br>
          <div class="upload_button">
            <%= f.file_field :image, accept: "image/jpeg,image/gif,image/png" %>
          </div>
          <div class="save_button">
            <%= f.submit 'Update', class:"btn btn-primary" %>
          </div>
        <% end %>
        <script type="text/javascript">
          $("#ingredient_image").bind("change", function() {
          var size_in_megabytes = this.files[0].size/1024/1024;
          if (size_in_megabytes > 5) {
            alert("Maximum file size is 5MB. Please choose a smaller file.");
            $("#ingredient_image").val("");
            }
          });
        </script>
    </div>
  </div>
</div>

app/views/ingredients/index.html.erb
<h1>Ingredients</h1>
</br>
</br>

 

<div class="header">
  <%= search_form_for @q, url: ingredients_path do |f| %>
    <div class="button_search_field">
        <div class="search_box">
         <%= f.search_field :name_cont, class:"search_field", placeholder: 'キーワードで検索する' %>
        </div>
        <div class="search_button">
          <%= button_tag :type => "submit", :class => "button_tag" do %>
            <i class="fas fa-search fa-2x index_search_icon"></i>
          <% end %>
        </div>
        <div class="add_button_parent">
          <div class="add_button">
            <%= link_to new_ingredient_path do %>
              <button type="button" class="btn btn-warning index_new_button">ADD</button>
            <% end %>
          </div>
        </div>
    </div>
  <% end %>
</div>

<div class="color_explanation">
  <div style="width:30px; height:30px; background:#D3E8C1;">
  </div>
  <div class="expiry_comment">
    ：賞味期限前
  </div>
  <div style="width:30px; height:30px; background:#ffe44b; margin-left:20px">
  </div>
  <div class="expiry_comment">
    ：賞味期限2日前
  </div>
  <div style="width:30px; height:30px; background:#f95454; margin-left:20px">
  </div>
  <div class="expiry_comment">
    ：賞味期限切れ
  </div>
</div>

<div class="container_parent">
  <div class="container_children">
    <% @ingredients.each do |ingredient| %>
      <% if ingredient.expiry < Date.today %> 
        <div class="item_red" style="width: 200px">
      <% elsif ingredient.expiry < Date.today + 2 %>
        <div class="item_yellow" style="width: 200px">
      <% else %>
        <div class="item" style="width: 200px">
      <% end %>
          <h5><%= ingredient.name %></h5>
          <%= link_to ingredient_path(ingredient) do %>
            <%= image_tag ingredient.display_image if ingredient.image.attached?%>
          <% end %>
          <div class="item_button">
            <%= link_to edit_ingredient_path(ingredient) do %>
              <button type="button" class="edit_button">編集</button>
            <% end %>
          </div>
          <div class="item_button">
            <%= link_to ingredient_path(ingredient), method: :delete, data: { confirm: "You sure?"} do %>
              <button type="button" class="delete_button">削除</button>
            <% end %>
          </div>
        </div>
    <% end %>
  </div>
</div>

<%= will_paginate%>

app/views/ingredients/new.html.erb
<h1>Ingredient Change</h1>

<div>
  <div class="container">
    <div class="row justify-content-md-center">
        <%= form_with(model: @ingredient, builder: WithErrorFormBuilder, url: ingredients_path, class: "col-md-auto", local: true) do |f| %>
          <%# <%= render 'shared/error_messages', model: f.object %> 
          <%= f.label :name, '食材' %> <%= f.text_field :name, class: 'form-control' %></br>
          <%= f.label :expiry, '賞味期限' %> <%= f.date_field :expiry, class: 'form-control'%></br>
          <%= f.label :number, '個数' %> <%= f.number_field :number, class: 'form-control'%></br>
          <%= f.label :amount, '重量(g)' %> <%= f.number_field :amount, class: 'form-control'%></br>
          <div class="upload_button">
            <%= f.file_field :image, accept: "image/jpeg,image/gif,image/png"  %>
          </div>
          <div class="save_button">
            <%= f.submit 'Save', class:"btn btn-primary" %>
          </div>
        <% end %>
        <script type="text/javascript">
          $("#ingredient_image").bind("change", function() {
          var size_in_megabytes = this.files[0].size/1024/1024;
          if (size_in_megabytes > 5) {
            alert("Maximum file size is 5MB. Please choose a smaller file.");
            $("#ingredient_image").val("");
            }
          });
        </script>
    </div>
  </div>
</div>

app/views/ingredients/show.html.erb
<%= render 'shared/show' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Frige</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'%>
    <!-- コード追加　Bootstrap CSS読み込みコード-->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.9.0/css/all.css"> 
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'%>
    <!-- コード追加　Bootstrap JavaScript読み込みコード-->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  </head>

  <body>
    <%# <div class="notifications">
      <% flash.each do |key, value| %>
        <%# <%= content_tag(:div, value, class: key)%>
      <%# <% end %>
    <%# </div> %> 
    <%= yield %>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if model.errors.any? %>
  <div class="alert alert-warning">
    <ul>
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_photos.html.erb
<%# 写真をクリックしたときの実行アクション（showなのでphoto_path(photo.id)）とリクエスト形式（jsなのでremote: true） を指定 %>
<%= link_to ingredient_path(ingredient.id), remote: true do %>
  <%= image_tag ingredient.display_image if ingredient.image.attached?, class: "photo-img", id: "photo-img" %>
<% end %>

app/views/shared/_show.html.erb
こおここ